export const DEFAULT_ICON: Record<string, { icon: string }> = {
  'lucide:code': {
    icon: 'lucide:code',
  },
  'simple-icons:juejin': { icon: 'simple-icons:juejin' },
  'simple-icons:github': { icon: 'simple-icons:github' },
  'lucide:camera': {
    icon: 'lucide:camera',
  },
  'simple-icons:xiaohongshu': { icon: 'simple-icons:xiaohongshu' },
  'simple-icons:tiktok': { icon: 'simple-icons:tiktok' },
  'lucide:pause': { icon: 'lucide:pause' },
  'lucide:play': { icon: 'lucide:play' },
  'lucide:briefcase': { icon: 'lucide:briefcase' },
  'material-symbols:image-outline': {
    icon: 'material-symbols:image-outline',
  },
  'material-symbols:restart-alt': {
    icon: 'material-symbols:restart-alt',
  },
  'mynaui:search': {
    icon: 'mynaui:search',
  },
  'carbon:close-outline': { icon: 'carbon:close-outline' },
  'stash:lock-closed': { icon: 'stash:lock-closed' },
  'stash:lock-opened': { icon: 'stash:lock-opened' },
  'tabler:history': { icon: 'tabler:history' },
  'fa-solid:chart-line': { icon: 'fa-solid:chart-line' },
  'fa-solid:caret-down': { icon: 'fa-solid:caret-down' },
  'fa-solid:caret-up': { icon: 'fa-solid:caret-up' },
  'material-symbols:delete-outline': { icon: 'material-symbols:delete-outline' },
  'formkit:close': { icon: 'formkit:close' },
  'bxs:hot': { icon: 'bxs:hot' },
  'fluent:apps-24-filled': { icon: 'fluent:apps-24-filled' },
  'fluent:align-left-24-filled': { icon: 'fluent:align-left-24-filled' },
  'material-symbols:article-shortcut-rounded': {
    icon: 'material-symbols:article-shortcut-rounded',
  },
  'pajamas:todo-done': { icon: 'pajamas:todo-done' },
  'ic:round-add': { icon: 'ic:round-add' },
  'iconamoon:settings-fill': { icon: 'iconamoon:settings-fill' },
  'mdi:fish': { icon: 'mdi:fish' },
  'lucide:refresh-cw': { icon: 'lucide:refresh-cw' },
  'lucide:heart': { icon: 'lucide:heart' },
  'mingcute:question-line': { icon: 'mingcute:question-line' },
  'famicons:chevron-back': { icon: 'famicons:chevron-back' },
  'twemoji:sun': { icon: 'twemoji:sun' },
  'ri:moon-clear-fill': { icon: 'ri:moon-clear-fill' },
  'fluent:search-24-regular': { icon: 'fluent:search-24-regular' },
  'ion:language': { icon: 'ion:language' },
  'ic:round-push-pin': { icon: 'ic:round-push-pin' },
  'pajamas:todo-add': { icon: 'pajamas:todo-add' },
  'ph:file-md-duotone': { icon: 'ph:file-md-duotone' },
  'fluent-mdl2:color-solid': { icon: 'fluent-mdl2:color-solid' },
  'icon-park-outline:send-one': { icon: 'icon-park-outline:send-one' },
  'ic:round-delete': { icon: 'ic:round-delete' },
  'logos:vue': { icon: 'logos:vue' },
  'logos:typescript-icon': { icon: 'logos:typescript-icon' },
  'logos:vitejs': { icon: 'logos:vitejs' },
  'logos:pinia': { icon: 'logos:pinia' },
  'logos:router': { icon: 'logos:router' },
  'logos:tailwindcss-icon': { icon: 'logos:tailwindcss-icon' },
  'logos:pnpm-icon': { icon: 'logos:pnpm-icon' },
  'logos:eslint': { icon: 'logos:eslint' },
  'logos:prettier-icon': { icon: 'logos:prettier-icon' },
  'logos:husky': { icon: 'logos:husky' },
  'mdi:file-document-outline': { icon: 'mdi:file-document-outline' },
  'mdi:hammer-wrench': { icon: 'mdi:hammer-wrench' },
  'mdi:file-code-outline': { icon: 'mdi:file-code-outline' },
  'mdi:git-commit': { icon: 'mdi:git-commit' },
  'mdi:code-tags': { icon: 'mdi:code-tags' },
  'logos:iconify': { icon: 'logos:iconify' },
  'logos:axios': { icon: 'logos:axios' },
  'logos:dayjs': { icon: 'logos:dayjs' },
  'mdi:image-plus': { icon: 'mdi:image-plus' },
  'mdi:file-pdf-box': { icon: 'mdi:file-pdf-box' },
  'mdi:grip-vertical': { icon: 'mdi:grip-vertical' },
  'mdi:calendar-clock': { icon: 'mdi:calendar-clock' },
  'mdi:translate': { icon: 'mdi:translate' },
  'logos:element': { icon: 'logos:element' },
  'fa6-solid:snowflake': { icon: 'fa6-solid:snowflake' },
  'mdi:github': { icon: 'mdi:github' },
  'tabler:external-link': { icon: 'tabler:external-link' },
}
