/**
 * 图标列表
 * 记录项目所有图标的信息，包括图标名称、颜色和名称
 */

interface IconItem {
  icon: string
  color?: string
  name?: string
}

export const ICON_LIST: Record<string, IconItem> = {
  'simple-icons:juejin': { icon: 'simple-icons:juejin', color: 'text-blue-500', name: '稀土掘金' },
  'simple-icons:github': { icon: 'simple-icons:github', color: 'text-black', name: 'GitHub' },
  'lucide:camera': {
    icon: 'lucide:camera',
  },
  'simple-icons:xiaohongshu': {
    icon: 'simple-icons:xiaohongshu',
    color: 'text-red-500',
    name: '小红书',
  },
  'logos:tiktok-icon': { icon: 'logos:tiktok-icon', name: '抖音' },
  'lucide:pause': { icon: 'lucide:pause', name: '暂停' },
  'lucide:play': { icon: 'lucide:play', name: '播放' },
  'lucide:briefcase': { icon: 'lucide:briefcase' },
  'material-symbols:image-outline': {
    icon: 'material-symbols:image-outline',
  },
  'material-symbols:restart-alt': {
    icon: 'material-symbols:restart-alt',
    name: '刷新',
  },
  'mynaui:search': {
    icon: 'mynaui:search',
    name: '搜索',
  },
  'carbon:close-outline': { icon: 'carbon:close-outline' },
  'stash:lock-closed': { icon: 'stash:lock-closed' },
  'stash:lock-opened': { icon: 'stash:lock-opened' },
  'tabler:history': { icon: 'tabler:history' },
  'fa-solid:chart-line': { icon: 'fa-solid:chart-line' },
  'fa-solid:caret-down': { icon: 'fa-solid:caret-down' },
  'fa-solid:caret-up': { icon: 'fa-solid:caret-up' },
  'formkit:close': { icon: 'formkit:close' },
  'bxs:hot': { icon: 'bxs:hot' },
  'fluent:apps-24-filled': { icon: 'fluent:apps-24-filled' },
  'fluent:align-left-24-filled': { icon: 'fluent:align-left-24-filled' },
  'material-symbols:article-shortcut-rounded': {
    icon: 'material-symbols:article-shortcut-rounded',
  },
  'pajamas:todo-done': { icon: 'pajamas:todo-done' },
  'ic:round-add': { icon: 'ic:round-add' },
  'iconamoon:settings-fill': { icon: 'iconamoon:settings-fill' },
  'mdi:fish': { icon: 'mdi:fish' },
  'lucide:refresh-cw': { icon: 'lucide:refresh-cw' },
  'solar:heart-bold': { icon: 'solar:heart-bold' },
  'mingcute:question-line': { icon: 'mingcute:question-line' },
  'ic:round-push-pin': { icon: 'ic:round-push-pin', name: '置顶' },
  'pajamas:todo-add': { icon: 'pajamas:todo-add' },
  'ph:file-md-duotone': { icon: 'ph:file-md-duotone' },
  'fluent-mdl2:color-solid': { icon: 'fluent-mdl2:color-solid' },
  'icon-park-outline:send-one': { icon: 'icon-park-outline:send-one' },
  'ic:round-delete': { icon: 'ic:round-delete', name: '删除' },
  'icon-park:drag': { icon: 'icon-park:drag', name: '拖动' },
  'logos:vue': { icon: 'logos:vue' },
  'logos:typescript-icon': { icon: 'logos:typescript-icon' },
  'logos:vitejs': { icon: 'logos:vitejs' },
  'logos:pinia': { icon: 'logos:pinia' },
  'logos:tailwindcss-icon': { icon: 'logos:tailwindcss-icon' },
  'logos:eslint': { icon: 'logos:eslint' },
  'mdi:file-document-outline': { icon: 'mdi:file-document-outline' },
  'mdi:hammer-wrench': { icon: 'mdi:hammer-wrench' },
  'mdi:file-code-outline': { icon: 'mdi:file-code-outline' },
  'mdi:code-tags': { icon: 'mdi:code-tags' },
  'logos:axios': { icon: 'logos:axios' },
  'mdi:image-plus': { icon: 'mdi:image-plus' },
  'mdi:file-pdf-box': { icon: 'mdi:file-pdf-box' },
  'mdi:calendar-clock': { icon: 'mdi:calendar-clock' },
  'mdi:translate': { icon: 'mdi:translate' },
  'fa6-solid:snowflake': { icon: 'fa6-solid:snowflake' },
  'tabler:external-link': { icon: 'tabler:external-link' },
  'mingcute:down-line': { icon: 'mingcute:down-line' },
  'fa7-solid:qrcode': { icon: 'fa7-solid:qrcode' },
  'basil:file-user-solid': { icon: 'basil:file-user-solid', color: 'text-blue-500' },
  'majesticons:music': { icon: 'majesticons:music' },
  'material-symbols:download': { icon: 'material-symbols:download' },
  'tabler:switch-3': { icon: 'tabler:switch-3', name: '切换' },
  'clarity:email-solid': { icon: 'clarity:email-solid', color: 'text-sf-theme' },
  'lucide:file-text': { icon: 'lucide:file-text' },
  'lucide:layout-template': { icon: 'lucide:layout-template' },
  'lucide:palette': { icon: 'lucide:palette' },
  'element-plus': { icon: 'logos:element' },
  'fa6-solid:award': { icon: 'fa6-solid:award' },
  'fa6-solid:bullseye': { icon: 'fa6-solid:bullseye' },
  'fa6-solid:check': { icon: 'fa6-solid:check' },
  'fa6-solid:check-circle': { icon: 'fa6-solid:check-circle' },
  'fa6-solid:edit': { icon: 'fa6-solid:edit' },
  'fa6-solid:fire': { icon: 'fa6-solid:fire' },
  'fa6-solid:history': { icon: 'fa6-solid:history' },
  'fa6-solid:magic': { icon: 'fa6-solid:magic' },
  'fa6-solid:mountain': { icon: 'fa6-solid:mountain' },
  'fa6-solid:pen': { icon: 'fa6-solid:pen' },
  'fa6-solid:redo': { icon: 'fa6-solid:redo' },
  'fa6-solid:rocket': { icon: 'fa6-solid:rocket' },
  'fa6-solid:seedling': { icon: 'fa6-solid:seedling' },
  'fa6-solid:share-alt': { icon: 'fa6-solid:share-alt' },
  'fa6-solid:signature': { icon: 'fa6-solid:signature' },
  'famicons:copy-outline': { icon: 'famicons:copy-outline' },
  'fluent:layout-column-one-third-left-24-regular': {
    icon: 'fluent:layout-column-one-third-left-24-regular',
  },
  'fluent:layout-column-one-third-right-24-regular': {
    icon: 'fluent:layout-column-one-third-right-24-regular',
  },
  'fluent:layout-column-three-24-regular': { icon: 'fluent:layout-column-three-24-regular' },
  'line-md:loading-twotone-loop': { icon: 'line-md:loading-twotone-loop' },
  'line-md:save': { icon: 'line-md:save' },
  'logos:dayjs': { icon: 'logos:dayjs' },
  'logos:husky': { icon: 'logos:husky' },
  'logos:iconify': { icon: 'logos:iconify' },
  'logos:pnpm-icon': { icon: 'logos:pnpm-icon' },
  'logos:prettier-icon': { icon: 'logos:prettier-icon' },
  'logos:router': { icon: 'logos:router' },
  'lucide:check': { icon: 'lucide:check' },
  'lucide:pencil': { icon: 'lucide:pencil' },
  'lucide:sparkles': { icon: 'lucide:sparkles' },
  'lucide:trash-2': { icon: 'lucide:trash-2' },
  'lucide:x': { icon: 'lucide:x' },
  'mdi:account': { icon: 'mdi:account' },
  'mdi:arrow-up': { icon: 'mdi:arrow-up' },
  'mdi:chart-pie': { icon: 'mdi:chart-pie' },
  'mdi:check-circle': { icon: 'mdi:check-circle' },
  'mdi:chevron-right': { icon: 'mdi:chevron-right' },
  'mdi:clock-outline': { icon: 'mdi:clock-outline' },
  'mdi:content-copy': { icon: 'mdi:content-copy' },
  'mdi:database': { icon: 'mdi:database' },
  'mdi:database-alert': { icon: 'mdi:database-alert' },
  'mdi:database-outline': { icon: 'mdi:database-outline' },
  'mdi:dots-horizontal': { icon: 'mdi:dots-horizontal', name: '更多' },
  'mdi:drag-variant': { icon: 'mdi:drag-variant' },
  'mdi:git-commit': { icon: 'mdi:git-commit' },
  'mdi:grip-vertical': { icon: 'mdi:grip-vertical' },
  'mdi:information-variant': { icon: 'mdi:information-variant' },
  'mdi:lock': { icon: 'mdi:lock' },
  'mdi:microphone': { icon: 'mdi:microphone' },
  'mdi:monitor-dashboard': { icon: 'mdi:monitor-dashboard' },
  'mdi:palette-outline': { icon: 'mdi:palette-outline' },
  'mdi:palette-swatch': { icon: 'mdi:palette-swatch' },
  'mdi:robot-excited-outline': { icon: 'mdi:robot-excited-outline' },
  'mdi:robot-outline': { icon: 'mdi:robot-outline' },
  'mdi:server-network': { icon: 'mdi:server-network' },
  'mdi:widgets': { icon: 'mdi:widgets' },
  'mingcute:arrow-down-line': { icon: 'mingcute:arrow-down-line' },
  'mingcute:arrow-right-line': { icon: 'mingcute:arrow-right-line' },
  'mingcute:arrow-right-up-line': { icon: 'mingcute:arrow-right-up-line' },
  'mingcute:close-line': { icon: 'mingcute:close-line' },
  'mingcute:code-line': { icon: 'mingcute:code-line' },
  'mingcute:eye-line': { icon: 'mingcute:eye-line' },
  'ph:arrow-u-up-left-duotone': { icon: 'ph:arrow-u-up-left-duotone' },
  'ph:arrows-clockwise-duotone': { icon: 'ph:arrows-clockwise-duotone' },
  'ph:brain-duotone': { icon: 'ph:brain-duotone' },
  'ph:caret-down-bold': { icon: 'ph:caret-down-bold' },
  'ph:chat-teardrop-dots-duotone': { icon: 'ph:chat-teardrop-dots-duotone' },
  'ph:chat-teardrop-dots-fill': { icon: 'ph:chat-teardrop-dots-fill' },
  'ph:chats-teardrop-duotone': { icon: 'ph:chats-teardrop-duotone' },
  'ph:copy-duotone': { icon: 'ph:copy-duotone' },
  'ph:gear-duotone': { icon: 'ph:gear-duotone' },
  'ph:info-duotone': { icon: 'ph:info-duotone' },
  'ph:lightning-duotone': { icon: 'ph:lightning-duotone' },
  'ph:list-duotone': { icon: 'ph:list-duotone' },
  'ph:magic-wand-duotone': { icon: 'ph:magic-wand-duotone' },
  'ph:paper-plane-right-fill': { icon: 'ph:paper-plane-right-fill' },
  'ph:plus-bold': { icon: 'ph:plus-bold' },
  'ph:push-pin-fill': { icon: 'ph:push-pin-fill' },
  'ph:push-pin-light': { icon: 'ph:push-pin-light' },
  'ph:snowflake-duotone': { icon: 'ph:snowflake-duotone' },
  'ph:stethoscope-duotone': { icon: 'ph:stethoscope-duotone' },
  'ph:stop-circle-fill': { icon: 'ph:stop-circle-fill' },
  'ph:trash-simple-duotone': { icon: 'ph:trash-simple-duotone' },
  'ph:user-circle-duotone': { icon: 'ph:user-circle-duotone' },
  'ph:user-duotone': { icon: 'ph:user-duotone' },
  'ph:x-bold': { icon: 'ph:x-bold' },
  'solar:danger-triangle-bold-duotone': { icon: 'solar:danger-triangle-bold-duotone' },
  'solar:hourglass-line-duotone': { icon: 'solar:hourglass-line-duotone' },
}
