/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfBacktop: typeof import('@components/business/backtop/index.vue')['default']
    SfBarrage: typeof import('@components/business/barrage/index.vue')['default']
    SfDropdown: typeof import('@components/business/dropdown/index.vue')['default']
    SfDynamicForm: typeof import('@components/business/dynamicForm/index.vue')['default']
    SfImg: typeof import('@components/business/img/index.vue')['default']
    SfInput: typeof import('@components/business/input/index.vue')['default']
    SfList: typeof import('@components/business/list/index.vue')['default']
    SfLocale: typeof import('@components/business/locale/index.vue')['default']
    SfMenu: typeof import('@components/business/menu/index.vue')['default']
    SfMixImg: typeof import('@components/business/mixImg/index.vue')['default']
    SfModal: typeof import('@components/business/modal/index.vue')['default']
    SfMonitor: typeof import('@components/business/monitor/index.vue')['default']
    SfQrcode: typeof import('@components/business/qrcode/index.vue')['default']
    SfScrollbarTab: typeof import('@components/business/scrollbarTab/index.vue')['default']
    SfSetBox: typeof import('@components/business/setBox/index.vue')['default']
    SfSetContainer: typeof import('@components/business/setContainer/index.vue')['default']
    SfSetItem: typeof import('@components/business/setItem/index.vue')['default']
    SfSetTitle: typeof import('@components/business/setTitle/index.vue')['default']
    SfTab: typeof import('@components/business/tab/index.vue')['default']
    SfTheme: typeof import('@components/business/theme/index.vue')['default']
    SfTooltip: typeof import('@components/business/tooltip/index.vue')['default']
    SfViewContainer: typeof import('@components/business/viewContainer/index.vue')['default']
  }
}
