/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfBacktop: typeof import('@components/business/backtop/index.vue')['default']
    SfLocale: typeof import('@components/business/locale/index.vue')['default']
    SfModal: typeof import('@components/business/modal/index.vue')['default']
    SfMonitor: typeof import('@components/business/monitor/index.vue')['default']
    SfTheme: typeof import('@components/business/theme/index.vue')['default']
    SfTooltip: typeof import('@components/business/tooltip/index.vue')['default']
  }
}
