/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfDropdown: typeof import('@components/business/dropdown/index.ts')['default']
    SfFooter: typeof import('@components/business/footer/index.ts')['default']
    SfImg: typeof import('@components/el/img/index.ts')['default']
    SfList: typeof import('@components/business/list/index.ts')['default']
    SfModal: typeof import('@components/business/modal/index.ts')['default']
    SfMonitor: typeof import('@components/business/monitor/index.ts')['default']
    SfScrollbar: typeof import('@components/el/scrollbar/index.ts')['default']
    SfSetBox: typeof import('@components/business/setBox/index.ts')['default']
    SfSetItem: typeof import('@components/business/setItem/index.ts')['default']
    SfSetTitle: typeof import('@components/business/setTitle/index.ts')['default']
    SfTooltip: typeof import('@components/business/tooltip/index.ts')['default']
  }
}
