/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfCollapse: typeof import('@components/el/collapse/index.ts')['default']
    SfCollapseItem: typeof import('@components/el/collapseItem/index.ts')['default']
    SfDatePicker: typeof import('@components/el/datePicker/index.ts')['default']
    SfDropdown: typeof import('@components/business/dropdown/index.ts')['default']
    SfDynamicForm: typeof import('@components/business/dynamicForm/index.ts')['default']
    SfEcharts: typeof import('@components/business/echarts/index.ts')['default']
    SfImg: typeof import('@components/el/img/index.ts')['default']
    SfInput: typeof import('@components/el/input/index.ts')['default']
    SfList: typeof import('@components/business/list/index.ts')['default']
    SfMenu: typeof import('@components/business/menu/index.ts')['default']
    SfMixImg: typeof import('@components/business/mixImg/index.ts')['default']
    SfModal: typeof import('@components/business/modal/index.ts')['default']
    SfMonitor: typeof import('@components/business/monitor/index.ts')['default']
    SfScrollbar: typeof import('@components/el/scrollbar/index.ts')['default']
    SfSelect: typeof import('@components/el/select/index.ts')['default']
    SfSetBox: typeof import('@components/business/setBox/index.ts')['default']
    SfSetContainer: typeof import('@components/business/setContainer/index.ts')['default']
    SfSetItem: typeof import('@components/business/setItem/index.ts')['default']
    SfSetTitle: typeof import('@components/business/setTitle/index.ts')['default']
    SfSlider: typeof import('@components/el/slider/index.ts')['default']
    SfTab: typeof import('@components/business/tab/index.ts')['default']
    SfTabPane: typeof import('@components/business/tabPane/index.ts')['default']
    SfTooltip: typeof import('@components/business/tooltip/index.ts')['default']
    SfWangEditor: typeof import('@components/business/wangEditor/index.ts')['default']
  }
}
