/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfBacktop: typeof import('@components/el/backtop/index.ts')['default']
    SfBarrage: typeof import('@components/business/barrage/index.ts')['default']
    SfDropdown: typeof import('@components/business/dropdown/index.ts')['default']
    SfFooter: typeof import('@components/business/footer/index.ts')['default']
    SfImg: typeof import('@components/el/img/index.ts')['default']
    SfList: typeof import('@components/business/list/index.ts')['default']
    SfModal: typeof import('@components/business/modal/index.ts')['default']
    SfMonitor: typeof import('@components/business/monitor/index.ts')['default']
    SfQrcode: typeof import('@components/business/qrcode/index.ts')['default']
    SfScrollbar: typeof import('@components/el/scrollbar/index.ts')['default']
    SfSetBox: typeof import('@components/business/setBox/index.ts')['default']
    SfSetItem: typeof import('@components/business/setItem/index.ts')['default']
    SfTooltip: typeof import('@components/business/tooltip/index.ts')['default']
    SfViewContainer: typeof import('@components/business/viewContainer/index.ts')['default']
  }
}
