interface IconItem {
  icon: string
  color?: string
  name?: string
}

export const ICON_LIST: Record<string, IconItem> = {
  'lucide:code': {
    icon: 'lucide:code',
  },
  'simple-icons:juejin': { icon: 'simple-icons:juejin', color: 'text-blue-500', name: '稀土掘金' },
  'simple-icons:github': { icon: 'simple-icons:github', color: 'text-black', name: 'GitHub' },
  'lucide:camera': {
    icon: 'lucide:camera',
  },
  'simple-icons:xiaohongshu': {
    icon: 'simple-icons:xiaohongshu',
    color: 'text-red-500',
    name: '小红书',
  },
  'logos:tiktok-icon': { icon: 'logos:tiktok-icon', name: '抖音' },
  'lucide:pause': { icon: 'lucide:pause' },
  'lucide:play': { icon: 'lucide:play' },
  'lucide:briefcase': { icon: 'lucide:briefcase' },
  'material-symbols:image-outline': {
    icon: 'material-symbols:image-outline',
  },
  'material-symbols:restart-alt': {
    icon: 'material-symbols:restart-alt',
  },
  'mynaui:search': {
    icon: 'mynaui:search',
  },
  'carbon:close-outline': { icon: 'carbon:close-outline' },
  'stash:lock-closed': { icon: 'stash:lock-closed' },
  'stash:lock-opened': { icon: 'stash:lock-opened' },
  'tabler:history': { icon: 'tabler:history' },
  'fa-solid:chart-line': { icon: 'fa-solid:chart-line' },
  'fa-solid:caret-down': { icon: 'fa-solid:caret-down' },
  'fa-solid:caret-up': { icon: 'fa-solid:caret-up' },
  'material-symbols:delete-outline': { icon: 'material-symbols:delete-outline', name: '删除' },
  'formkit:close': { icon: 'formkit:close' },
  'bxs:hot': { icon: 'bxs:hot' },
  'fluent:apps-24-filled': { icon: 'fluent:apps-24-filled' },
  'fluent:align-left-24-filled': { icon: 'fluent:align-left-24-filled' },
  'material-symbols:article-shortcut-rounded': {
    icon: 'material-symbols:article-shortcut-rounded',
  },
  'pajamas:todo-done': { icon: 'pajamas:todo-done' },
  'ic:round-add': { icon: 'ic:round-add' },
  'iconamoon:settings-fill': { icon: 'iconamoon:settings-fill' },
  'mdi:fish': { icon: 'mdi:fish' },
  'lucide:refresh-cw': { icon: 'lucide:refresh-cw' },
  'lucide:heart': { icon: 'lucide:heart' },
  'mingcute:question-line': { icon: 'mingcute:question-line' },
  'famicons:chevron-back': { icon: 'famicons:chevron-back' },
  'twemoji:sun': { icon: 'twemoji:sun' },
  'ri:moon-clear-fill': { icon: 'ri:moon-clear-fill' },
  'fluent:search-24-regular': { icon: 'fluent:search-24-regular' },
  'ion:language': { icon: 'ion:language' },
  'ic:round-push-pin': { icon: 'ic:round-push-pin', name: '置顶' },
  'pajamas:todo-add': { icon: 'pajamas:todo-add' },
  'ph:file-md-duotone': { icon: 'ph:file-md-duotone' },
  'fluent-mdl2:color-solid': { icon: 'fluent-mdl2:color-solid' },
  'icon-park-outline:send-one': { icon: 'icon-park-outline:send-one' },
  'ic:round-delete': { icon: 'ic:round-delete', name: '删除' },
  'logos:vue': { icon: 'logos:vue' },
  'logos:typescript-icon': { icon: 'logos:typescript-icon' },
  'logos:vitejs': { icon: 'logos:vitejs' },
  'logos:pinia': { icon: 'logos:pinia' },
  'logos:tailwindcss-icon': { icon: 'logos:tailwindcss-icon' },
  'logos:eslint': { icon: 'logos:eslint' },
  'mdi:file-document-outline': { icon: 'mdi:file-document-outline' },
  'mdi:hammer-wrench': { icon: 'mdi:hammer-wrench' },
  'mdi:file-code-outline': { icon: 'mdi:file-code-outline' },
  'mdi:code-tags': { icon: 'mdi:code-tags' },
  'logos:axios': { icon: 'logos:axios' },
  'mdi:image-plus': { icon: 'mdi:image-plus' },
  'mdi:file-pdf-box': { icon: 'mdi:file-pdf-box' },
  'mdi:calendar-clock': { icon: 'mdi:calendar-clock' },
  'mdi:translate': { icon: 'mdi:translate' },
  'logos:element': { icon: 'logos:element' },
  'fa6-solid:snowflake': { icon: 'fa6-solid:snowflake' },
  'mdi:github': { icon: 'mdi:github' },
  'tabler:external-link': { icon: 'tabler:external-link' },
  'mingcute:up-line': { icon: 'mingcute:up-line' },
  'mingcute:down-line': { icon: 'mingcute:down-line' },
  'fa7-solid:qrcode': { icon: 'fa7-solid:qrcode' },
  'basil:file-user-solid': { icon: 'basil:file-user-solid', color: 'text-blue-500' },
  'majesticons:music': { icon: 'majesticons:music' },
  'material-symbols:download': { icon: 'material-symbols:download' },
  'tabler:switch-3': { icon: 'tabler:switch-3' },
  'clarity:email-solid': { icon: 'clarity:email-solid', color: 'text-sf-theme' },
}
